### ISSUE TITLE
mkit-gcc and mkit-armcc repo locations

### ISSUE THREAD

**Issue by jacobrosenthal** [ARMmbed/target-nrf51822#30]
Doesnt really belong here, but I cant find where they're hosted. Google has some broken links
github.com/armmbed/target-mkit-gcc
github.com/armmbed/targe-mkit-gcc

And the yotta info doesnt include their git location. Can someone link them or just PR the git into their yotta info.
http://yotta.mbed.com/#/target/mkit-gcc/0.0.8

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1263

**Comment by rgrover** [comment]
@jacobrosenthal  This has now been fixed. Please close the issue once you are satisfied.
