### ISSUE TITLE
Merge nordic targets to reduce code duplication

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/target-nrf51822#31]
There is a lot of code duplicated between the targets nordic-nrf51822-16k-gcc and nordic-nrf51822-32k-gcc (similarly for the ARMCC targets). These targets can be merged into a single one and yotta config macros defined to control whether the end target is 16k or 32k target.

**Comment by jacobrosenthal** [comment]
This actually fixes a separate issue I have which is that its currently impossible to link these targets from repo or fork them, because yotta doesnt support the ability to pick the targets out of a repo subdirectory.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1271

**Comment by andresag01** [comment]
@jacobrosenthal Note that a proposal change is in place in the referenced pull request. However, I do not think this will solve the inherit problem in yotta that you are experiencing (i.e. https://github.com/ARMmbed/yotta/issues/566) because so far we are planning to add the new targets to the existing repository rather than creating new "single target-single repo" solutions.

**Comment by andresag01** [comment]
A repo for the new targets has been created. Furthermore, the new targets `nordic-nrf51822-gcc` and `nordic-nrf51822-armcc` that replace `nordic-nrf51822-16k-gcc`, `nordic-nrf51822-16k-armcc`, `nordic-nrf51822-32k-gcc` and `nordic-nrf51822-32k-armcc` have been published in the yotta registry.
